config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('memo.urls')),
]

memo/urls.py
from django.urls import path

from . import views

app_name = 'memo'

urlpatterns = [
    path('', views.MemoListView.as_view(), name='memo_list'),
    path('memo_create/', views.MemoCreateView.as_view(), name='memo_create'),
    path('update_add_tag/', views.update_add_tag, name='update_add_tag'),
]

memo/models.py
# models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(
        verbose_name='タグ名',
        max_length=127,
    )
    def __str__(self):
        return self.name

class Memo(models.Model):
    title = models.CharField(
        verbose_name='タイトル',
        max_length=255,
    )
    content = models.TextField(
        verbose_name='本文',
        blank=True,
        null=True,
    )
    tags = models.ManyToManyField(
        Tag,
        verbose_name='タグ',
        blank=True,
    )
    created_at = models.DateTimeField(
        verbose_name='作成日時',
        auto_now=True,
    )

    def __str__(self):
        return self.title

memo/forms.py
from django.forms import ModelForm

from .models import Memo


class MemoCreateForm(ModelForm):
    class Meta:
        model = Memo
        fields = ('title', 'content', 'tags')

memo/views.py
from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import View
from django.urls import reverse_lazy, reverse

from django.http import HttpResponse, HttpResponseRedirect

import logging
logger = logging.getLogger(__name__)


from django.shortcuts import render, redirect

from .models import Memo, Tag
from .forms import MemoCreateForm

class MemoListView(ListView):
    model = Memo
    template_name = 'memo_list.html'

    def get_queryset(self):
        memo_list = Memo.objects.all().order_by('-created_at')
        return memo_list

class MemoCreateView(View):

    def get(self, request, *args, **kwargs):
        tag_list = Tag.objects.all()
        context = {
            'tag_list': tag_list,
        }
        return render(request, 'memo_create.html', context)

    def post(self, request, *args, **kwargs):
        if request.POST["title"] != "":
            memo = Memo(title=request.POST['title'], content=request.POST['content'])
            memo.save()
            for tag in request.POST.getlist('tags'):
                memo.tags.add(tag)
        return redirect(reverse('memo:memo_list'))


# タグのアップデート
def update_add_tag(request):
    if request.POST["tag_name"] != "":
        name = Tag.objects.filter(name=request.POST["tag_name"])
        if len(name) == 0:
            tag = Tag(name=request.POST["tag_name"])
            tag.save()
    return HttpResponseRedirect(reverse('memo:memo_create'))

memo/templates/memo_create.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>Memo Create</title>
</head>
<body>
<form method="post" action="{% url 'memo:memo_create' %}">
  {% csrf_token %}
  <table>
    <tbody>
    <tr>
      <th><label for="title">タイトル:</label></th>
      <td><input type="text" name="title" maxlength="255" required id="title" kl_vkbd_parsed="true"></td>
    </tr>
    <tr>
      <th><label for="content">本文:</label></th>
      <td><textarea name="content" cols="40" rows="10" id="content"></textarea></td>
    </tr>
    <tr>
      <th><label for="tags">タグ:</label></th>
      <td><select name="tags" multiple>
        {% for tag in tag_list %}
        <option value="{{ tag.pk }}">{{ tag.name }}</option>
        {% endfor %}
      </select></td>
    </tr>
    </tbody>
  </table>
  <button type="submit">作成</button>
</form>

<form method="post" action="{% url 'memo:update_add_tag' %}">
  {% csrf_token %}
  <label for="tag_name">新規タグ:</label>
  <input type="text" name="tag_name" maxlength="127" required><button type="submit">作成</button>
</form>
</body>
</html>

memo/templates/memo_list.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>Memo List</title>
</head>
<body>
<a href="{% url 'memo:memo_create' %}">新規メモ作成</a>
<table border="2">
  <thead>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>タグ</th>
  </tr>
  </thead>
  <tbody>
  {% for memo in memo_list %}
  <tr>
    <td>{{ memo.title }}</td><td>{{ memo.content }}</td>
    <td>
      {% for tag in  memo.tags.all %}
        「{{ tag.name }}」
      {% endfor %}
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>
</body>
</html>